FROM ocaml/opam2:ubuntu-18.04-ocaml-4.07 AS build-env

# Build SATySFi
ENV SATYSFI_VERSION=0.0.3+dev2019.07.14
RUN opam repository add satysfi-external https://github.com/gfngfn/satysfi-external-repo.git
RUN opam repository add satyrographos-repo https://github.com/na4zagin3/satyrographos-repo.git
RUN git pull && opam update
RUN opam depext satysfi.${SATYSFI_VERSION} satysfi-lib-dist.${SATYSFI_VERSION}
RUN opam install satysfi.${SATYSFI_VERSION} satysfi-lib-dist.${SATYSFI_VERSION}
RUN opam pin add https://github.com/na4zagin3/satyrographos.git # to use latest satyrographos
RUN eval $(opam env) && \
  satyrographos install -copy && \
  cp $(which satysfi) /home/opam/ && \
  cp $(which satyrographos) /home/opam/

# --

FROM ubuntu:18.04

# Copy from build-env
COPY --from=build-env /home/opam/.satysfi /usr/local/share/satysfi
COPY --from=build-env /home/opam/satysfi /usr/local/bin/satysfi
COPY --from=build-env /home/opam/satyrographos /usr/local/bin/satyrographos

# Setup build directory
RUN mkdir /satysfi
WORKDIR /satysfi
