name: base
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name of the image (e.g., opam-2.0.7-ocaml-4.11.1)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: base
          file: base/Dockerfile
          push: true
          tags: ghcr.io/amutake/satysfi-base-image:${{ github.event.inputs.tag }}
          platforms: linux/amd64,linux/arm64
