name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [Dockerfile, Dockerfile.slim, Dockerfile.head]
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.dockerfile }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.dockerfile }}-
      - id: args
        run:
          echo "::set-output name=date::$(date --iso-8601=seconds)"
          echo "::set-output name=revision::$(git rev-parse --short HEAD)"
      - uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.dockerfile }}
          push: false
          tags: amutake/satysfi:ci
          build-args: |
            BUILD_DATE=${{ steps.args.outputs.date }}
            VERSION=ci
            REVISION=${{ steps.args.outputs.revision }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - run: git clone git://github.com/gfngfn/SATySFi.git
      - run: docker run --rm -v $(pwd)/SATySFi/demo:/satysfi amutake/satysfi:ci satysfi demo.saty
