name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: .
            opam-available: true
          - context: slim
            opam-available: false
          - context: head
            opam-available: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.context }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.context }}-
      - id: args
        run: |
          echo "::set-output name=date::$(date --iso-8601=seconds)"
          echo "::set-output name=revision::$(git rev-parse --short HEAD)"
      - uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          push: false
          load: true
          tags: amutake/satysfi:ci
          build-args: |
            BUILD_DATE=${{ steps.args.outputs.date }}
            VERSION=ci
            REVISION=${{ steps.args.outputs.revision }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      # tests
      - run: docker run --rm amutake/satysfi:ci satysfi --help
      - run: docker run --rm amutake/satysfi:ci satyrographos help
      - run: docker run --rm -v $(pwd)/tests:/satysfi amutake/satysfi:ci satysfi minimum.saty
      - run: docker run --rm -v $(pwd)/tests:/satysfi amutake/satysfi:ci satysfi with-dist.saty
      - run: docker run --rm -v $(pwd)/tests:/satysfi amutake/satysfi:ci sh -c "opam install satysfi-base && satyrographos install && satysfi with-dist.saty"
        if: ${{ matrix.opam-available }}
