name: nightly
on:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
      - uses: actions/checkout@v1
      - run: echo $DOCKERHUB_ACCESS_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
      - run: |
          docker build -t amutake/satysfi:nightly -f Dockerfile.head \
            --build-arg BUILD_DATE=$(date --iso-8601=seconds) \
            --build-arg VERSION=$(date --iso-8601=date)-nightly \
            --build-arg REVISION=$(git rev-parse --short HEAD) .
      - run: git clone git://github.com/gfngfn/SATySFi.git
      - run: docker run --rm -v $(pwd)/SATySFi/demo:/satysfi amutake/satysfi:nightly satysfi demo.saty
      - run: docker push amutake/satysfi:nightly
