name: nightly
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - id: args
        run: |
          echo "::set-output name=date::$(date --iso-8601=seconds)"
          echo "::set-output name=version::$(date --iso-8601=date)-nightly"
          echo "::set-output name=revision::$(git rev-parse --short HEAD)"
      - uses: docker/build-push-action@v2
        with:
          file: Dockerfile.head
          push: false
          load: true
          tags: amutake/satysfi:nightly
          build-args: |
            BUILD_DATE=${{ steps.args.outputs.date }}
            VERSION=${{ steps.args.outputs.version }}
            REVISION=${{ steps.args.outputs.revision }}
      - run: git clone git://github.com/gfngfn/SATySFi.git
      - run: docker run --rm -v $(pwd)/SATySFi/demo:/satysfi amutake/satysfi:nightly satysfi demo.saty
      - run: docker push amutake/satysfi:nightly
