name: nightly
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          # - linux/arm64
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - id: args
        run: |
          echo "date=$(date --iso-8601=seconds)" >> $GITHUB_OUTPUT
          echo "version=$(date --iso-8601=date)-nightly" >> $GITHUB_OUTPUT
          echo "revision=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v5
        with:
          context: head
          file: head/Dockerfile
          push: false
          load: true
          tags: amutake/satysfi:nightly
          build-args: |
            BUILD_DATE=${{ steps.args.outputs.date }}
            VERSION=${{ steps.args.outputs.version }}
            REVISION=${{ steps.args.outputs.revision }}
          platforms: ${{ matrix.platform }}
      # run tests
      - run: docker run --rm amutake/satysfi:nightly satysfi --help
      - run: docker run --rm amutake/satysfi:nightly satyrographos help
      - run: docker run --rm -v $(pwd)/tests:/satysfi amutake/satysfi:nightly satysfi minimum.saty
      - run: docker run --rm -v $(pwd)/tests:/satysfi amutake/satysfi:nightly satysfi with-dist.saty
      - run: git clone https://github.com/gfngfn/SATySFi.git
      - run: docker run --rm -v $(pwd)/SATySFi/demo:/satysfi amutake/satysfi:nightly satysfi demo.saty
      # push
      - run: docker push amutake/satysfi:nightly
