on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [Dockerfile, Dockerfile.slim, Dockerfile.head]
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t amutake/satysfi:ci -f ${{ matrix.dockerfile }} .
      - run: git clone git://github.com/gfngfn/SATySFi.git
      - run: docker run --rm -v $(pwd)/SATySFi/demo:/satysfi amutake/satysfi:ci satysfi /satysfi/demo.saty
