name: release
on:
  release:
    types: [published]

jobs:
  full:
    runs-on: ubuntu-latest
    env:
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      TAG: ${GITHUB_REF#refs/tags/}
    steps:
      - uses: actions/checkout@v1
      - run: docker login -u amutake -p $DOCKER_PASS
      - run: docker build -t amutake/satysfi:${TAG} -f Dockerfile .
      - run: docker tag amutake/satysfi:${TAG} amutake/satysfi:latest
      - run: docker push amutake/satysfi:${TAG}
      - run: docker push amutake/satysfi:latest
  slim:
    runs-on: ubuntu-latest
    env:
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      TAG: ${GITHUB_REF#refs/tags/}
    steps:
      - uses: actions/checkout@v1
      - run: docker login -u amutake -p $DOCKER_PASS
      - run: docker build -t amutake/satysfi:${TAG}-slim -f Dockerfile.slim .
      - run: docker tag amutake/satysfi:${TAG}-slim amutake/satysfi:slim
      - run: docker push amutake/satysfi:${TAG}-slim
      - run: docker push amutake/satysfi:slim
