name: release
on:
  release:
    types: [published]

jobs:
  full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - run: |
          docker build -t amutake/satysfi:${{ steps.get_version.outputs.version }} \
            -f Dockerfile \
            --build-arg BUILD_DATE=$(date --iso-8601=seconds) \
            --build-arg VERSION=${{ steps.get_version.outputs.version }} \
            --build-arg REVISION=$(git rev-parse --short HEAD) .
      - run: docker tag amutake/satysfi:${{ steps.get_version.outputs.version }} amutake/satysfi:latest
      - run: docker push amutake/satysfi:${{ steps.get_version.outputs.version }}
      - run: docker push amutake/satysfi:latest
  slim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - run: |
          docker build -t amutake/satysfi:${{ steps.get_version.outputs.version }}-slim \
            -f Dockerfile.slim \
            --build-arg BUILD_DATE=$(date --iso-8601=seconds) \
            --build-arg VERSION=${{ steps.get_version.outputs.version }}-slim \
            --build-arg REVISION=$(git rev-parse --short HEAD) .
      - run: docker tag amutake/satysfi:${{ steps.get_version.outputs.version }}-slim amutake/satysfi:slim
      - run: docker push amutake/satysfi:${{ steps.get_version.outputs.version }}-slim
      - run: docker push amutake/satysfi:slim
