name: release
on:
  release:
    types: [published]

jobs:
  info:
    outputs:
      date: ${{ steps.info.outputs.version }}
      version: ${{ steps.info.outputs.version }}
      revision: ${{ steps.info.outputs.revision }}
    runs-on: ubuntu-latest
    steps:
      - id: info
        run: |
          echo "::set-output name=date::$(date --iso-8601=seconds)"
          echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
          echo "::set-output name=revision::$(git rev-parse --short HEAD)"

  full:
    needs: info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-Dockerfile-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-Dockerfile-
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: |
            amutake/satysfi:latest
            amutake/satysfi:${{ needs.info.outputs.version }}
          build-args: |
            BUILD_DATE=${{ needs.info.outputs.date }}
            VERSION=${{ needs.info.outputs.version }}
            REVISION=${{ needs.info.outputs.revision }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  slim:
    needs: info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-Dockerfile.slim-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-Dockerfile.slim-
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          file: Dockerfile.slim
          push: true
          tags: |
            amutake/satysfi:slim
            amutake/satysfi:${{ needs.info.outputs.version }}-slim
          build-args: |
            BUILD_DATE=${{ needs.info.outputs.date }}
            VERSION=${{ needs.info.outputs.version }}
            REVISION=${{ needs.info.outputs.revision }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
