name: release
on:
  release:
    types: [published]

jobs:
  info:
    outputs:
      date: ${{ steps.info.outputs.date }}
      version: ${{ steps.info.outputs.version }}
      revision: ${{ steps.info.outputs.revision }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: info
        run: |
          echo "date=$(date --iso-8601=seconds)" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "revision=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT          
  release:
    needs: info
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: .
            tag: ${{ needs.info.outputs.version }}
            tag-alias: latest
          - context: slim
            tag: ${{ needs.info.outputs.version }}-slim
            tag-alias: slim
          - context: opam-slim
            tag: ${{ needs.info.outputs.version }}-opam-slim
            tag-alias: opam-slim
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.context }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.context }}-
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          push: true
          tags: |
            amutake/satysfi:${{ matrix.tag }}
            amutake/satysfi:${{ matrix.tag-alias }}
          build-args: |
            BUILD_DATE=${{ needs.info.outputs.date }}
            VERSION=${{ matrix.tag }}
            REVISION=${{ needs.info.outputs.revision }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
